[project]
name = "vgc-standings"
version = "0.0.0"
requires-python = ">=3.10"
dependencies = [
    "paste-parser",
    "reportworm-builder",
]

[dependency-groups]
dev = [
    "ruff>=0.14.14",
]

[tool.uv.sources]
reportworm-builder = { git = "https://github.com/mikewVGC/reportworm-builder.git" }
paste-parser = { git = "https://github.com/mikewVGC/paste-parser.git" }
